# # A lot of the styles we want can only be configured
# # using unstable features.
# #
# # If you have trouble running rustfmt, try "cargo +nightly fmt".
# unstable_features = true

edition = "2021"
